name: Test de la función de ejemplo Suma.

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalamos Node.js
        run: npm install

      - name: Ejecutamos los tests
        run: npm test